create table public.time_deposits
(
    balance                        numeric(38, 2) not null,
    day_of_deposit                 integer not null,
    for_date                       date,
    id                             integer generated by default as identity primary key,
    last_interest_calculation_date date,
    next_interest_calculation_date date,
    version                        integer,
    created_at                     timestamp(6) with time zone,
    updated_at                     timestamp(6) with time zone,
    plan_type                      varchar(255)
);

create table public.withdrawals
(
    amount         numeric(38, 2) not null,
    date           date not null,
    id             integer generated by default as identity primary key,
    time_deposit_id integer
        constraint fkqkg2h07nleh4m0duhtrcde9q7
            references public.time_deposits,
    created_at     timestamp(6) with time zone,
    plan_type      varchar(255) not null
);
