spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time-deposit-db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml

time-deposit:
  default:
    decimal-places: 2
    first-interest-calculation-day: 30
  plans:
    basic:
        first-interest-calculation-day: ${time-deposit.default.first-interest-calculation-day}
        decimal-places: ${time-deposit.default.decimal-places}
        interest-rate: 0.01
    student:
        first-interest-calculation-day: ${time-deposit.default.first-interest-calculation-day}
        last-interest-calculation-day: 366
        decimal-places: ${time-deposit.default.decimal-places}
        interest-rate: 0.03
    premium:
        first-interest-calculation-day: 45
        decimal-places: ${time-deposit.default.decimal-places}
        interest-rate: 0.05

interest-recalculation:
  cron: '0 0 0 * * *'