spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time-deposit-db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml