services:
  postgres:
    image: postgres:latest
    container_name: time-deposit-postgres
    environment:
      POSTGRES_DB: time-deposit-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
